//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1_Cource3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbi_ShippingDetails
    {
        public int ShippingDetailsId { get; set; }
        public Nullable<int> memberId { get; set; }
        public string Adress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<decimal> AmontPaid { get; set; }
        public string PaymentType { get; set; }
    
        public virtual Tbi_Members Tbi_Members { get; set; }
    }
}
